#!/usr/bin/env python
# Rewrite for better multi-cam results
import rospy
from typing import List
import cv2
import cv2.aruco as aruco
import numpy as np
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CameraInfo
from geometry_msgs.msg import TransformStamped
import tf.transformations
from visualization_msgs.msg import Marker, MarkerArray
import tf2_ros
from std_srvs.srv import Trigger, TriggerResponse
import tf
import argparse
import sys

class MultiCameraArucoNode:
    def __init__(self, camera_ids: list[str], im_topic: str = "/color/image_raw", 
                 inf_topic: str = "/color/camera_info", aruco_dict: str = "DICT_4X4_50", 
                 marker_len: float = 0.06):
        
        rospy.init_node("multicam_aruco")
        self.camera_ids = camera_ids
        self.aruco_dict = aruco_dict
        self.marker_length = marker_len

        self.image_subscribers = []
        #self.info_topics = []

        # Lists of the topics we need to listen to
        for cam_id in camera_ids:
            #self.image_topics.append(f"/{cam_id}/{im_topic}")
            self.image_subscribers.append(rospy.Subscriber(f"/{cam_id}/{im_topic}", Image, self.image_callback))
            #self.info_topics.append(f"/{cam_id}/{inf_topic}")

        rospy.loginfo(f"Multicamera aruco node initialized with cameas: {camera_ids}")


        self.bridge = CvBridge()
        

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="This node detects an aruco marker, and publishes the transform from each camera")

    parser.add_argument('-c', '--cameras', nargs='?', help="Comma-separated camera IDS, defauls to 'camera'.", default='camera')

    args = parser.parse_args()
    
    mine = args.cameras.split(',')

    try:
        node = MultiCameraArucoNode(camera_ids=mine)
        node.spin()
    except rospy.ROSInterruptException:
        pass
