#!/usr/bin/env python
import rospy
import cv2
import cv2.aruco as aruco
import numpy as np
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CameraInfo
from geometry_msgs.msg import TransformStamped
import tf.transformations
from visualization_msgs.msg import Marker, MarkerArray
import tf2_ros
from std_srvs.srv import Trigger, TriggerResponse
import tf
import argparse
import sys
from multiprocessing import Process
from time import sleep
import tf

# This node wraps OpenCVs aruco library to ros

class CameraArucoDetector:
    def __init__(self, camera_id, image_topic, cam_info_topic, aruco_dict_name, marker_length):
        rospy.init_node(f'aruco_{camera_id}')
        
        self.camera_id = camera_id
        self.image_topic = image_topic
        self.cam_info_topic = cam_info_topic
        self.marker_length = marker_length  # in meters
        self.bridge = CvBridge()
        self.camera_matrix = None
        self.dist_coeffs = None
        self.camera_frame = None
        self.latest_detections = []  # Each detection: (marker_id, rvec, tvec, corners)
        
        # Subscribers for image and camera info
        self.image_sub = rospy.Subscriber(self.image_topic, Image, self.image_callback)
        self.cam_info_sub = rospy.Subscriber(self.cam_info_topic, CameraInfo, self.cam_info_callback)
        
        # TF broadcaster to publish marker transforms relative to the camera frame
        self.tf_broadcaster = tf2_ros.TransformBroadcaster()
        # Publisher for visualization in RViz (MarkerArray)
        self.marker_pub = rospy.Publisher(f"/aruco_markers_{camera_id}", MarkerArray, queue_size=10)
        
        # Create the ArUco dictionary and detector parameters
        self.aruco_dict = aruco.getPredefinedDictionary(getattr(aruco, aruco_dict_name))
        self.aruco_params = aruco.DetectorParameters()
        self.detector = aruco.ArucoDetector(self.aruco_dict, self.aruco_params)

        self.calibrated = False # We only need the calibration to occur once unless requested
        self.lastTransform = None

        self.tf_listen = tf.TransformListener()
        
        
        rospy.loginfo(f"{camera_id} aruco node is UP")
        rospy.spin()

    def cam_info_callback(self, msg):
        # Save camera calibration parameters (only once)
        if self.camera_matrix is None:
            self.camera_matrix = np.array(msg.K).reshape((3, 3))
            self.dist_coeffs = np.array(msg.D)
            self.camera_frame = msg.header.frame_id
            rospy.loginfo("Camera '{}' calibration received.".format(self.camera_id))
            # Unsubscribe after receiving calibration
            self.cam_info_sub.unregister()

    def image_callback(self, msg):
        if self.camera_matrix is None:
            # Cannot process image until calibration parameters are available.
            return
        elif self.calibrated == True:
            # Camera is static, so we don't need to keep doing image maths
            self.lastTransform.header.stamp = rospy.Time.now()
            self.tf_broadcaster.sendTransform(self.lastTransform)
            return
        try:
            #rospy.loginfo(f"Camera '{self.camera_id}' image received.")
            cv_image = self.bridge.imgmsg_to_cv2(msg, desired_encoding="bgr8")
        except Exception as e:
            rospy.logerr("CV Bridge error in camera '{}': {}".format(self.camera_id, e))

        # Detect markers
        corners, ids, _ = self.detector.detectMarkers(cv_image)

        marker_array = MarkerArray()
        if ids is not None: # If marker is detected

            # Estimate pose for each detected marker
            rvecs, tvecs, _ = aruco.estimatePoseSingleMarkers(corners, self.marker_length, 
                                                               self.camera_matrix, self.dist_coeffs)
            for i, marker_id in enumerate(ids.flatten()):

                rvec = rvecs[i]
                tvec = tvecs[i]

                # Convert rotation vector to matrix

                # Draw marker and axis for debugging (optional)
                aruco.drawDetectedMarkers(cv_image, corners, ids)
                cv2.drawFrameAxes(cv_image, self.camera_matrix, self.dist_coeffs, rvec, tvec, self.marker_length * 0.5)
                
            
                
                self.lastdet = rospy.get_time()

                # Convert rotation vector to quaternion
                R_matrix, _ = cv2.Rodrigues(rvec)
                current_q = self.rotation_matrix_to_quaternion(R_matrix)
                current_t = tvec[0] #Flatten

                smooth_t = current_t
                smooth_q = current_q

                self.tf_listen.waitForTransform(f"{self.camera_id}_link", self.camera_frame, rospy.Time(0), rospy.Duration(0.1))
                (trans, rot) = self.tf_listen.lookupTransform(f"{self.camera_id}_link", self.camera_frame, rospy.Time(0))

                link_to_frame = tf.transformations.concatenate_matrices(
                    tf.transformations.translation_matrix(trans),
                    tf.transformations.quaternion_matrix(rot)
                )

                frame_to_link = tf.transformations.inverse_matrix(link_to_frame)

                frame_to_tag = tf.transformations.concatenate_matrices(
                    tf.transformations.translation_matrix(smooth_t),
                    tf.transformations.quaternion_matrix(smooth_q)
                )

                tag_to_frame = tf.transformations.inverse_matrix(frame_to_tag)

                tag_to_cam = tf.transformations.concatenate_matrices(tag_to_frame, frame_to_link)
                # combined = tf.transformations.inverse_matrix(combined)
                final_t = tf.transformations.translation_from_matrix(tag_to_cam)
                final_q = tf.transformations.quaternion_from_matrix(tag_to_cam)


                
                t = TransformStamped()
                t.header.stamp = msg.header.stamp
                
                t.header.frame_id = f"marker_{marker_id}"
                t.child_frame_id = f"{self.camera_id}_link" #self.camera_frame
                #t.child_frame_id = f"{self.camera_id}_marker_{marker_id}"
                #t.header.frame_id = self.camera_frame
                
                t.transform.translation.x = final_t[0]
                t.transform.translation.y = final_t[1]
                t.transform.translation.z = final_t[2]
                t.transform.rotation.x = final_q[0]
                t.transform.rotation.y = final_q[1]
                t.transform.rotation.z = final_q[2]
                t.transform.rotation.w = final_q[3]

                self.lastTransform = t
                self.calibrated = True
                self.tf_broadcaster.sendTransform(self.lastTransform)

                # Create a visualization marker for RViz
                marker = Marker()
                marker.header.frame_id = self.camera_frame
                marker.header.stamp = msg.header.stamp
                marker.ns = "{}_aruco".format(self.camera_id)
                marker.id = marker_id
                marker.type = Marker.CUBE
                marker.action = Marker.ADD
                marker.pose.position.x = smooth_t[0]
                marker.pose.position.y = smooth_t[1]
                marker.pose.position.z = smooth_t[2]
                marker.pose.orientation.x = smooth_q[0]
                marker.pose.orientation.y = smooth_q[1]
                marker.pose.orientation.z = smooth_q[2]
                marker.pose.orientation.w = smooth_q[3]
                marker.scale.x = self.marker_length
                marker.scale.y = self.marker_length
                marker.scale.z = 0.005  # Thin marker visualization
                marker.color.a = 0.8
                marker.color.r = 0.0
                marker.color.g = 1.0
                marker.color.b = 0.0
                marker_array.markers.append(marker)

                # Publish the MarkerArray for visualization in RViz
                self.marker_pub.publish(marker_array)
            
        # Optionally, display the processed image (for debugging)
        cv2.imshow(f"cam_{self.camera_id}", cv_image)
        cv2.waitKey(1)

    def rotation_matrix_to_quaternion(self, R_matrix):
        # Build a 4x4 homogeneous transformation matrix
        M = np.eye(4)
        M[0:3, 0:3] = R_matrix
        # Use tf.transformations to convert rotation matrix to quaternion
        quat = tf.transformations.quaternion_from_matrix(M)
        return quat

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="This node detects an aruco marker, and publishes the transform from each camera")

    parser.add_argument('-c', '--camera', nargs='?', help="camera id, defauls to 'camera'.", default='camera')

    argv = rospy.myargv()[1:] # this works for some reason I dont understand
    args = parser.parse_args(argv)
    
    cam_id = args.camera.split(',')[0]

    try:
        node = CameraArucoDetector(cam_id, f"/{cam_id}/color/image_raw", f"/{cam_id}/color/camera_info",
                                   "DICT_6X6_50", 0.12)
    except rospy.ROSInterruptException:
        pass
