#!/usr/bin/env python3

import rospy
from visualization_msgs.msg import Marker
from art_detection.msg import HandLandmark3D, HandResult3D
import argparse
from multiprocessing import Process
from time import sleep

###
# This file turns published HandResult3D(s) into marker points
# This is just for Rviz Visualisation.
###

class HandVisualizer:
    
    # landmarks: The points to visualize. If empty, all points published in the hand
    #            topic will be visualized.
    def __init__(self, cameras=[""], landmarks=[]):
        rospy.init_node('hand_visualizer')

        self.sub = {}
        self.pub = {}

        for handTopic3d in cameras:
            self.pub[handTopic3d] = rospy.Publisher(f'{handTopic3d}/hand_marker', Marker, queue_size=10)
            self.sub[handTopic3d] = rospy.Subscriber(f"{handTopic3d}/hand_3d", HandResult3D, self._hand_callback, (handTopic3d))

        self.landmarks = landmarks
        self.frame_id = None

        rospy.spin()

    def _hand_callback(self, msg: HandResult3D, args: list):
        camera = args

        self.frame_id = msg.header.frame_id
        
        marker = Marker()
        marker.header.stamp = rospy.Time.now()
        marker.header.frame_id = self.frame_id
        marker.scale.x = 0.03
        marker.scale.y = 0.03
        marker.scale.z = 0.03
        marker.color.g = 1
        marker.color.a = 0.7
        marker.type = 8 # A series of cubes
        marker.points = []

        for landmark in msg.landmarks:
            landmark: HandLandmark3D
            if self.landmarks == [] or landmark in self.landmarks:
                marker.points.append(landmark.point)
        
        self.pub[camera].publish(marker)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("-c", "--cameras", nargs="?", type=str, default="")
    argv = rospy.myargv()[1:]
    args = parser.parse_args(argv)

    cameras = args.cameras.split(',')
    rospy.loginfo(f"Starting Hand3D Marker Node with: {cameras}")
    print("#" + str(cameras))

    HandVisualizer(cameras=cameras)
