#!/usr/bin/env python3

import argparse
from hands import Hands

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Art detects and publisht the information of spotted hands")

    parser.add_argument('--imageTopic2D', nargs='?', type=str, default="/camera/color/image_raw", help="The ROS topic which has the image input")
    parser.add_argument('--depthTopic', nargs='?', type=str, default="/camera/aligned_depth_to_color/image_raw", help="The ROS topic which has the depth image input")
    parser.add_argument('--infoTopic', nargs='?', type=str, default="/camera/aligned_depth_to_color/camera_info", help="The ROS topic which has the depth image camera information")



    parser.add_argument('--rate', nargs='?', type=int, default=60, help="The maximum rate of detection from this node")

    args = parser.parse_args()
    Hands.main(**vars(args))